name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore      
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal       
   
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.site4now.net/qrcubeapp/
        ftp-username: serviciostesting-001
        ftp-password: ${{ secrets.FTP_PASSWORD }}
  
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{ secrets.API_KEY }}
        MESSAGE: "Una nueva publicacion link http://qrcubeapp.eurekani.com/!"




