name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: 'Deploy to UAT'
      uses: januszmarcinik/ftp-deploy@v1
      with:
        server: ftp://ftp.site4now.net/qrcubeapp/
        user: serviciostesting-001
        password: ${{ secrets.FTP_PASSWORD }}
        localRoot: bin/Debug/netcoreapp3.1/publish/      
  
      
