name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    - name: Upload bundle
      uses: bayssmekanique/action-simple-file-upload@v1
      with:
        user: serviciostesting-001
        password: ${{ secrets.FTP_PASSWORD }}
        host: ftp://ftp.site4now.net
        src: bin
        dest: qrcubeapp/
    


