name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    
    - name: Upload public_html via FTP
        uses: airvzxf/ftp-deployment-action@v1.0-alpha.1
        with:
          server: ftp://ftp.site4now.net/qrcubeapp/
          user: serviciostesting-001
          password: ${{ secrets.FTP_PASSWORD }}
          delete: "true"
          local_dir: "bin"
      


