name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal       
    - name: Publish
      run: |
        dotnet publish -c Release -o dotnetcorewebapp2 
        
  
    - name: Publish
      uses: isthatcentered/dist-to-ftp@master
      with:
          user: serviciostesting-001 # Ftp user Ex:
          password: ${{ secrets.FTP_PASSWORD }} # Ftp password Ex:
          host: ftp.site4now.net/ # Ftp host Ex:
          path: dotnetcorewebapp2/ # Folder to deploy Ex: apps/frontend/dist or dist
          into: qrcubeapp # Where to place the files in your ftp
          cleanupExisting: true # (Optional), Remove already ex
     
  
