name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal       
    - name: Publish
      run: |
        dotnet publish -c Release -o dotnetcorewebapp2 
    
    - name: Upload bundle
      uses: bayssmekanique/action-simple-file-upload@v1
      with:
        user: serviciostesting-001
        password: ${{ secrets.FTP_PASSWORD }}
        host: ftp.site4now.net
        src: dotnetcorewebapp2/
        dest: qrcubeapp
  
    -
     
  
